# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import correio_pb2 as correio__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in correio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CorreioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCartas = channel.unary_stream(
                '/Correio/GetCartas',
                request_serializer=correio__pb2.Endereco.SerializeToString,
                response_deserializer=correio__pb2.Carta.FromString,
                _registered_method=True)
        self.SendCartas = channel.unary_unary(
                '/Correio/SendCartas',
                request_serializer=correio__pb2.Carta.SerializeToString,
                response_deserializer=correio__pb2.Endereco.FromString,
                _registered_method=True)


class CorreioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCartas(self, request, context):
        """recebe um endereço do cliente e retorna as respectivas cartas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCartas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CorreioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCartas': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCartas,
                    request_deserializer=correio__pb2.Endereco.FromString,
                    response_serializer=correio__pb2.Carta.SerializeToString,
            ),
            'SendCartas': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCartas,
                    request_deserializer=correio__pb2.Carta.FromString,
                    response_serializer=correio__pb2.Endereco.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Correio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Correio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Correio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCartas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Correio/GetCartas',
            correio__pb2.Endereco.SerializeToString,
            correio__pb2.Carta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCartas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Correio/SendCartas',
            correio__pb2.Carta.SerializeToString,
            correio__pb2.Endereco.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
